# Generated by Django 3.2.2 on 2021-12-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='motioncontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=3)),
                ('camera', models.CharField(max_length=3)),
                ('radar', models.CharField(max_length=3)),
                ('sonar', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automated_Mode', models.CharField(max_length=3)),
                ('manual_Mode', models.CharField(max_length=3)),
                ('Path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimain.aisource')),
            ],
        ),
    ]
