# Generated by Django 3.2.2 on 2021-12-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='Path',
        ),
    ]
